<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title); 
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('JYLibrary', array(
        'action'=>'add'));?>">Add new album</a></p>
<?php if(isset($albums)){?>
<table class="table">
<tr>
	<th>id</th>
    <th>Title</th>
    <th>Artist</th>
    
</tr>

<?php foreach($albums as $album) : ?>
<tr>
	<td><?php echo $this->escapeHtml($album->id);?></td>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
</tr>
<?php endforeach; ?>
</table>
<?php } ?>