<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>广西建设职业技术学院移动图书馆</title>
<link rel="stylesheet" href="/js/jq/jquery.mobile-1.0a2.min.css">
<style type="text/css">
.homeb1 {	
	height: 150px;
	width: 150px;
	float: left;
	margin: 4px;
	display: block;
}
.homeb2 {
	height: 150px;
	width: 150px;
	float: left;
	margin: 4px;
	display: block;
}
.homeb3 {
	height: 150px;
	width: 150px;
	float: left;
	margin: 4px;
	display: block;
}
.homeb4 {
	height: 150px;
	width: 150px;
	float: left;
	margin: 4px;
	display: block;
}
.homebTxt
{
	font-size:24px;
	font-weight:bold;
	position:relative;
	top:100px;
	left:10px;
	color:#FFF;
	float:left;
}
.homebImg{
	top:12px;
	right:12px;
	position:relative;
}

.news {
	float: left;
	border: thin dotted #333;
	clear: both;
	width:320px;
}
.LiteralTitlelink {
    background: url("../skin/hd.gif") no-repeat scroll 0 8px #FFFFFF;
    float: left;
	 margin: 0;
    padding: 0;
	text-align: left;
	 font-size: 12px;
}
.LiteralTitlelink li{
	margin:0;
	padding:0;

}
</style>
<script src="/js/jq/jquery-1.4.4.min.js"></script>
<script src="/js/jq/jquery.mobile-1.0a2.min.js"></script>



</head>
<body>

<!-- Page starts here -->
<div data-role="page" data-theme="b" id="page1">
  <div data-role="header" id="hdrMain" name="hdrMain" data-nobackbtn="true">
    <h1><img src="/images/logo.png"></h1>
  </div>
  <div data-role="content" id="contentMain" name="contentMain">
  <div class="homeCenter">
   <div class="homeb1">
<a href="index.html">
	<img alt="馆藏资源" src="/images/homeButton1.png" />
    </a>
</div>

 <div class="homeb1">
<a href="index.html">
	<img alt="电子资源" src="/images/homeButton2.png" />
    </a>
</div>

<div class="homeb1">
<a href="index.html">
	<img alt="我的书房" src="/images/homeButton3.png" />
    </a>
</div>

<div class="homeb1">
<a href="index.html">
	<img alt="软件设置" src="/images/homeButton4.png" />
    </a>
</div>

 <br/>  
<div class="news">
<span>最新通知</span>
<ul>
        <li>
           <span class="LiteralTitlelink"><a title="请各位老师下载2013年5月份新书推荐目录的通知" target="_blank" href="Contents.aspx?Type=2&amp;Id=129">请各位老师下载2013年5月份新书...2013-05-27</a></span>
        </li>
        <li>
           <span class="LiteralTitlelink"><a title="图书馆开通博看人文畅销期刊数据库试用的通知" target="_blank" href="Contents.aspx?Type=2&amp;Id=125">图书馆开通博看人文畅销期刊数据库试用的通...2013-05-13</a></span>
        </li>
    </ul>
</div>

   </div>
   
   
   </div>

<!-- contentMain -->

</body>
</html>
